#!/bin/bash

diff <(./bin/asciilines ./tests/bad_file/bad_canvas/bad.tvg) ./tests/bad_file/bad_canvas/expected_output
# The return code of the previous arg is $? For readability
# we put this in a variable result
result=$?

if [ $result -eq 0 ]
then
	echo 'Test was a success!'
else
	if [ $result -eq 1 ]
	then
		echo 'Test failed! Expected output did not match program output'
	else
		echo 'Test failed! Bash file broke somewhere'
	fi
fi
